import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

const satoshi = localFont({
  variable: "--font-satoshi",
  src: './fonts/satoshi.woff2',
});

export const metadata: Metadata = {
  title: "Byte Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${satoshi.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-foreground flex flex-col">
        {children}
      </body>
    </html>
  );
}
